spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learnify
    username: learnify
    password: secret
  jpa:
    hibernate:
      ddl-auto: update  
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
